[window]
opacity = 1.0
padding = { x = 10, y = 10 }
decorations = "none"

[font]
size = 13

[font.normal]
#family = "Hack Nerd Font Mono"
family = "UbuntuMono Nerd Font Mono"

[mouse]
hide_when_typing = true

[colors.primary]
background = "#121923"
foreground = "#cdcecf"

[colors.normal]
black   = "#393b44"
red     = "#c94f6d"
green   = "#81b29a"
yellow  = "#dbc074"
blue    = "#719cd6"
magenta = "#9d79d6"
cyan    = "#63cdcf"
white   = "#dfdfe0"

[colors.bright]
black   = "#575860"
red     = "#d16983"
green   = "#8ebaa4"
yellow  = "#e0c989"
blue    = "#86abdc"
magenta = "#baa1e2"
cyan    = "#7ad5d6"
white   = "#e4e4e5"
